-- Clean BSL_Speakers data with user_id connections
-- This script removes duplicates and adds proper user_id relationships

-- First, clear any existing data
TRUNCATE TABLE public.BSL_Speakers CASCADE;

-- Insert clean speaker data with user_id mappings
-- Note: All speakers start with NULL user_id until they register
-- The user_id can be updated later when speakers create accounts

INSERT INTO public.BSL_Speakers (id, name, title, linkedin, bio, imageurl, tags, availability, created_at, company, twitter, updated_at, user_id) VALUES

-- Edward Calderon - the main speaker (user_id will be set later when user registers)
('edward-calderon-speaker', 'Edward Calderon', 'Tech Lead & Blockchain Expert', 'https://linkedin.com/in/edward-calderon', 'Edward Calderon is a technology leader and blockchain expert with extensive experience in developing innovative solutions. He specializes in blockchain technology, smart contracts, and decentralized applications.', 'https://blockchainsummit.la/wp-content/uploads/2025/09/foto-edward-calderon.png', '{blockchain,technology,leadership,innovation}', '[]', NOW(), 'HashPass', 'https://twitter.com/edward-calderon', NOW(), NULL),

-- Key speakers (without user_id for now - they can be added later when they register)
('claudia-restrepo', 'Claudia Restrepo', 'Rectora', 'https://linkedin.com/in/claudia-restrepo', 'Experienced professional in Rectora at EAFIT.', 'https://blockchainsummit.la/wp-content/uploads/2025/09/foto-claudia-restrepo.png', '{Blockchain,FinTech,Innovation}', '{"friday": {"end": "17:00", "start": "09:00"}, "monday": {"end": "17:00", "start": "09:00"}, "tuesday": {"end": "17:00", "start": "09:00"}, "thursday": {"end": "17:00", "start": "09:00"}, "wednesday": {"end": "17:00", "start": "09:00"}}', NOW(), 'EAFIT', 'https://twitter.com/claudia-restrepo', NOW(), NULL),

('leonardo-villar', 'Leonardo Villar', 'Gerente General', 'https://linkedin.com/in/leonardo-villar', 'Experienced professional in Gerente General at Banco de la República.', 'https://blockchainsummit.la/wp-content/uploads/2025/09/foto-leonardo-villar.png', '{Blockchain,FinTech,Innovation}', '{"friday": {"end": "17:00", "start": "09:00"}, "monday": {"end": "17:00", "start": "09:00"}, "tuesday": {"end": "17:00", "start": "09:00"}, "thursday": {"end": "17:00", "start": "09:00"}, "wednesday": {"end": "17:00", "start": "09:00"}}', NOW(), 'Banco de la República', 'https://twitter.com/leonardo-villar', NOW(), NULL),

('cesar-ferrari', 'César Ferrari', 'Superintendente Financiero de Colombia', 'https://linkedin.com/in/cesar-ferrari', 'Experienced professional in Superintendente Financiero de Colombia at Superintendencia Financiera.', 'https://blockchainsummit.la/wp-content/uploads/2025/09/foto-cesar-ferrari.png', '{Blockchain,FinTech,Innovation}', '{"friday": {"end": "17:00", "start": "09:00"}, "monday": {"end": "17:00", "start": "09:00"}, "tuesday": {"end": "17:00", "start": "09:00"}, "thursday": {"end": "17:00", "start": "09:00"}, "wednesday": {"end": "17:00", "start": "09:00"}}', NOW(), 'Superintendencia Financiera', 'https://twitter.com/cesar-ferrari', NOW(), NULL),

('alberto-naudon', 'Alberto Naudon', 'Consejero', 'https://linkedin.com/in/alberto-naudon', 'Experienced professional in Consejero at Banco Central de Chile.', 'https://blockchainsummit.la/wp-content/uploads/2025/09/foto-alberto-naudon.png', '{Blockchain,FinTech,Innovation}', '{"friday": {"end": "17:00", "start": "09:00"}, "monday": {"end": "17:00", "start": "09:00"}, "tuesday": {"end": "17:00", "start": "09:00"}, "thursday": {"end": "17:00", "start": "09:00"}, "wednesday": {"end": "17:00", "start": "09:00"}}', NOW(), 'Banco Central de Chile', 'https://twitter.com/alberto-naudon', NOW(), NULL),

('jose-outumuro', 'José Outumuro', 'Director Institutional sales EMEA', 'https://linkedin.com/in/jose-outumuro', 'Experienced professional in Director Institutional sales EMEA at Crypto.com.', 'https://blockchainsummit.la/wp-content/uploads/2025/09/foto-jose-outumuro.png', '{Blockchain,FinTech,Innovation}', '{"friday": {"end": "17:00", "start": "09:00"}, "monday": {"end": "17:00", "start": "09:00"}, "tuesday": {"end": "17:00", "start": "09:00"}, "thursday": {"end": "17:00", "start": "09:00"}, "wednesday": {"end": "17:00", "start": "09:00"}}', NOW(), 'Crypto.com', 'https://twitter.com/jose-outumuro', NOW(), NULL),

('efrain-barraza', 'Efraín Barraza', 'Regional Expansion Manager - Latam', 'https://linkedin.com/in/efrain-barraza', 'Experienced professional in Regional Expansion Manager - Latam at Tether.', 'https://blockchainsummit.la/wp-content/uploads/2025/09/foto-efrain-barraza.png', '{Blockchain,FinTech,Innovation}', '{"friday": {"end": "17:00", "start": "09:00"}, "monday": {"end": "17:00", "start": "09:00"}, "tuesday": {"end": "17:00", "start": "09:00"}, "thursday": {"end": "17:00", "start": "09:00"}, "wednesday": {"end": "17:00", "start": "09:00"}}', NOW(), 'Tether', 'https://twitter.com/efrain-barraza', NOW(), NULL),

('sandra-meza', 'Sandra Meza', 'Vicepresidente Control Interno y Cumplimiento', 'https://linkedin.com/in/sandra-meza', 'Experienced professional in Vicepresidente Control Interno y Cumplimiento at BBVA.', 'https://blockchainsummit.la/wp-content/uploads/2025/09/foto-sandra-meza.png', '{Blockchain,FinTech,Innovation}', '{"friday": {"end": "17:00", "start": "09:00"}, "monday": {"end": "17:00", "start": "09:00"}, "tuesday": {"end": "17:00", "start": "09:00"}, "thursday": {"end": "17:00", "start": "09:00"}, "wednesday": {"end": "17:00", "start": "09:00"}}', NOW(), 'BBVA', 'https://twitter.com/sandra-meza', NOW(), NULL),

('sebastian-duran', 'Sebastián Durán', 'Subdirector de Regulación', 'https://linkedin.com/in/sebastian-duran', 'Experienced professional in Subdirector de Regulación at Superintendencia Financiera de Colombia.', 'https://blockchainsummit.la/wp-content/uploads/2025/09/foto-sebastian-duran.png', '{Blockchain,FinTech,Innovation}', '{"friday": {"end": "17:00", "start": "09:00"}, "monday": {"end": "17:00", "start": "09:00"}, "tuesday": {"end": "17:00", "start": "09:00"}, "thursday": {"end": "17:00", "start": "09:00"}, "wednesday": {"end": "17:00", "start": "09:00"}}', NOW(), 'Superintendencia Financiera de Colombia', 'https://twitter.com/sebastian-duran', NOW(), NULL),

('rocelo-lopes', 'Rocelo Lopes', 'CEO', 'https://linkedin.com/in/rocelo-lopes', 'Experienced professional in CEO at SmartPay.', 'https://blockchainsummit.la/wp-content/uploads/2025/09/foto-rocelo-lopes.png', '{Blockchain,FinTech,Innovation}', '{"friday": {"end": "17:00", "start": "09:00"}, "monday": {"end": "17:00", "start": "09:00"}, "tuesday": {"end": "17:00", "start": "09:00"}, "thursday": {"end": "17:00", "start": "09:00"}, "wednesday": {"end": "17:00", "start": "09:00"}}', NOW(), 'SmartPay', 'https://twitter.com/rocelo-lopes', NOW(), NULL),

('ana-garces', 'Ana Garcés', 'Chief Compliance Officer', 'https://linkedin.com/in/ana-garces', 'Experienced professional in Chief Compliance Officer at Banco BHD.', 'https://blockchainsummit.la/wp-content/uploads/2025/09/foto-ana-garces.png', '{Blockchain,FinTech,Innovation}', '{"friday": {"end": "17:00", "start": "09:00"}, "monday": {"end": "17:00", "start": "09:00"}, "tuesday": {"end": "17:00", "start": "09:00"}, "thursday": {"end": "17:00", "start": "09:00"}, "wednesday": {"end": "17:00", "start": "09:00"}}', NOW(), 'Banco BHD', 'https://twitter.com/ana-garces', NOW(), NULL),

-- Additional key speakers
('juan-carlos-reyes', 'Juan Carlos Reyes', 'Presidente', 'https://linkedin.com/in/juan-carlos-reyes', 'Experienced professional in Presidente at Comisión Nacional de Activos Digitales (CNAD) El Salvador.', 'https://blockchainsummit.la/wp-content/uploads/2025/09/foto-juan-carlos-reyes.png', '{Blockchain,FinTech,Innovation}', '{"friday": {"end": "17:00", "start": "09:00"}, "monday": {"end": "17:00", "start": "09:00"}, "tuesday": {"end": "17:00", "start": "09:00"}, "thursday": {"end": "17:00", "start": "09:00"}, "wednesday": {"end": "17:00", "start": "09:00"}}', NOW(), 'Comisión Nacional de Activos Digitales (CNAD) El Salvador', 'https://twitter.com/juan-carlos-reyes', NOW(), NULL),

('gabriel-santos', 'Gabriel Santos', 'Presidente Ejecutivo', 'https://linkedin.com/in/gabriel-santos', 'Experienced professional in Presidente Ejecutivo at Colombia FinTech.', 'https://blockchainsummit.la/wp-content/uploads/2025/09/foto-gabriel-santos.png', '{Blockchain,FinTech,Innovation}', '{"friday": {"end": "17:00", "start": "09:00"}, "monday": {"end": "17:00", "start": "09:00"}, "tuesday": {"end": "17:00", "start": "09:00"}, "thursday": {"end": "17:00", "start": "09:00"}, "wednesday": {"end": "17:00", "start": "09:00"}}', NOW(), 'Colombia FinTech', 'https://twitter.com/gabriel-santos', NOW(), NULL),

('daniel-mangabeira', 'Daniel Mangabeira', 'Vice President Strategy & Policy, Brazil & Latin America', 'https://linkedin.com/in/daniel-mangabeira', 'Experienced professional in Vice President Strategy & Policy, Brazil & Latin America at Circle.', 'https://blockchainsummit.la/wp-content/uploads/2025/09/foto-daniel-mangabeira.png', '{Blockchain,FinTech,Innovation}', '{"friday": {"end": "17:00", "start": "09:00"}, "monday": {"end": "17:00", "start": "09:00"}, "tuesday": {"end": "17:00", "start": "09:00"}, "thursday": {"end": "17:00", "start": "09:00"}, "wednesday": {"end": "17:00", "start": "09:00"}}', NOW(), 'Circle', 'https://twitter.com/daniel-mangabeira', NOW(), NULL),

('willian-santos', 'Willian Santos', 'Gerente de Compliance - Oficial de Cumplimiento', 'https://linkedin.com/in/willian-santos', 'Experienced professional in Gerente de Compliance - Oficial de Cumplimiento at Banco W.', 'https://blockchainsummit.la/wp-content/uploads/2025/09/foto-willian-santos.png', '{Blockchain,FinTech,Innovation}', '{"friday": {"end": "17:00", "start": "09:00"}, "monday": {"end": "17:00", "start": "09:00"}, "tuesday": {"end": "17:00", "start": "09:00"}, "thursday": {"end": "17:00", "start": "09:00"}, "wednesday": {"end": "17:00", "start": "09:00"}}', NOW(), 'Banco W', 'https://twitter.com/willian-santos', NOW(), NULL),

('steffen-harting', 'Steffen Härting', 'Senior Manager', 'https://linkedin.com/in/steffen-harting', 'Experienced professional in Senior Manager at Deloitte: Crypto Asset Markets.', 'https://blockchainsummit.la/wp-content/uploads/2025/09/foto-steffen-harting.png', '{Blockchain,FinTech,Innovation}', '{"friday": {"end": "17:00", "start": "09:00"}, "monday": {"end": "17:00", "start": "09:00"}, "tuesday": {"end": "17:00", "start": "09:00"}, "thursday": {"end": "17:00", "start": "09:00"}, "wednesday": {"end": "17:00", "start": "09:00"}}', NOW(), 'Deloitte: Crypto Asset Markets', 'https://twitter.com/steffen-harting', NOW(), NULL),

('andres-florido', 'Andres Florido', 'Senior Manager - Blockchain & AI Assurance', 'https://linkedin.com/in/andres-florido', 'Experienced professional in Senior Manager - Blockchain & AI Assurance at Deloitte.', 'https://blockchainsummit.la/wp-content/uploads/2025/09/foto-andres-florido.png', '{Blockchain,FinTech,Innovation}', '{"friday": {"end": "17:00", "start": "09:00"}, "monday": {"end": "17:00", "start": "09:00"}, "tuesday": {"end": "17:00", "start": "09:00"}, "thursday": {"end": "17:00", "start": "09:00"}, "wednesday": {"end": "17:00", "start": "09:00"}}', NOW(), 'Deloitte', 'https://twitter.com/andres-florido', NOW(), NULL),

('andres-meneses', 'Andrés Meneses', 'Founder', 'https://linkedin.com/in/andres-meneses', 'Experienced professional in Founder at Orbyt X.', 'https://blockchainsummit.la/wp-content/uploads/2025/09/foto-andres-meneses.png', '{Blockchain,FinTech,Innovation}', '{"friday": {"end": "17:00", "start": "09:00"}, "monday": {"end": "17:00", "start": "09:00"}, "tuesday": {"end": "17:00", "start": "09:00"}, "thursday": {"end": "17:00", "start": "09:00"}, "wednesday": {"end": "17:00", "start": "09:00"}}', NOW(), 'Orbyt X', 'https://twitter.com/andres-meneses', NOW(), NULL),

('luther-maday', 'Luther Maday', 'Head of Payments', 'https://linkedin.com/in/luther-maday', 'Experienced professional in Head of Payments at Algorand Foundation.', 'https://blockchainsummit.la/wp-content/uploads/2025/09/foto-luther-maday.png', '{Blockchain,FinTech,Innovation}', '{"friday": {"end": "17:00", "start": "09:00"}, "monday": {"end": "17:00", "start": "09:00"}, "tuesday": {"end": "17:00", "start": "09:00"}, "thursday": {"end": "17:00", "start": "09:00"}, "wednesday": {"end": "17:00", "start": "09:00"}}', NOW(), 'Algorand Foundation', 'https://twitter.com/luther-maday', NOW(), NULL),

('albi-rodriguez', 'Albi Rodríguez', 'Senior Web3 & DLT Consultant', 'https://linkedin.com/in/albi-rodriguez', 'Experienced professional in Senior Web3 & DLT Consultant at Independent.', 'https://blockchainsummit.la/wp-content/uploads/2025/09/foto-albi-rodriguez.png', '{Blockchain,FinTech,Innovation}', '{"friday": {"end": "17:00", "start": "09:00"}, "monday": {"end": "17:00", "start": "09:00"}, "tuesday": {"end": "17:00", "start": "09:00"}, "thursday": {"end": "17:00", "start": "09:00"}, "wednesday": {"end": "17:00", "start": "09:00"}}', NOW(), 'Independent', 'https://twitter.com/albi-rodriguez', NOW(), NULL),

('judith-vergara', 'Judith Vergara', 'Director of Executive Education', 'https://linkedin.com/in/judith-vergara', 'Experienced professional in Director of Executive Education at Universidad EAFIT.', 'https://blockchainsummit.la/wp-content/uploads/2025/09/foto-judith-vergara.png', '{Blockchain,FinTech,Innovation}', '{"friday": {"end": "17:00", "start": "09:00"}, "monday": {"end": "17:00", "start": "09:00"}, "tuesday": {"end": "17:00", "start": "09:00"}, "thursday": {"end": "17:00", "start": "09:00"}, "wednesday": {"end": "17:00", "start": "09:00"}}', NOW(), 'Universidad EAFIT', 'https://twitter.com/judith-vergara', NOW(), NULL),

('william-duran', 'William Durán', 'CO-CEO & Founder', 'https://linkedin.com/in/william-duran', 'Experienced professional in CO-CEO & Founder at Minteo.', 'https://blockchainsummit.la/wp-content/uploads/2025/09/foto-william-duran.png', '{Blockchain,FinTech,Innovation}', '{"friday": {"end": "17:00", "start": "09:00"}, "monday": {"end": "17:00", "start": "09:00"}, "tuesday": {"end": "17:00", "start": "09:00"}, "thursday": {"end": "17:00", "start": "09:00"}, "wednesday": {"end": "17:00", "start": "09:00"}}', NOW(), 'Minteo', 'https://twitter.com/william-duran', NOW(), NULL),

('daniel-aguilar', 'Daniel Aguilar', 'Co Founder & COO', 'https://linkedin.com/in/daniel-aguilar', 'Experienced professional in Co Founder & COO at Trokera.', 'https://blockchainsummit.la/wp-content/uploads/2025/09/foto-daniel-aguilar.png', '{Blockchain,FinTech,Innovation}', '{"friday": {"end": "17:00", "start": "09:00"}, "monday": {"end": "17:00", "start": "09:00"}, "tuesday": {"end": "17:00", "start": "09:00"}, "thursday": {"end": "17:00", "start": "09:00"}, "wednesday": {"end": "17:00", "start": "09:00"}}', NOW(), 'Trokera', 'https://twitter.com/daniel-aguilar', NOW(), NULL),

('rafael-gago', 'Rafael Gago', 'Director Comercial, Gerencia de Ideación e Incubación', 'https://linkedin.com/in/rafael-gago', 'Experienced professional in Director Comercial, Gerencia de Ideación e Incubación at nuam exchange.', 'https://blockchainsummit.la/wp-content/uploads/2025/09/foto-rafael-gago.png', '{Blockchain,FinTech,Innovation}', '{"friday": {"end": "17:00", "start": "09:00"}, "monday": {"end": "17:00", "start": "09:00"}, "tuesday": {"end": "17:00", "start": "09:00"}, "thursday": {"end": "17:00", "start": "09:00"}, "wednesday": {"end": "17:00", "start": "09:00"}}', NOW(), 'nuam exchange', 'https://twitter.com/rafael-gago', NOW(), NULL),

('pablo-santos', 'Pablo Santos', 'Founder & CEO', 'https://linkedin.com/in/pablo-santos', 'Experienced professional in Founder & CEO at Finaktiva.', 'https://blockchainsummit.la/wp-content/uploads/2025/09/foto-pablo-santos.png', '{Blockchain,FinTech,Innovation}', '{"friday": {"end": "17:00", "start": "09:00"}, "monday": {"end": "17:00", "start": "09:00"}, "tuesday": {"end": "17:00", "start": "09:00"}, "thursday": {"end": "17:00", "start": "09:00"}, "wednesday": {"end": "17:00", "start": "09:00"}}', NOW(), 'Finaktiva', 'https://twitter.com/pablo-santos', NOW(), NULL),

('ana-maria-zuluaga', 'Ana María Zuluaga', 'Head of Open Finance Office', 'https://linkedin.com/in/ana-maria-zuluaga', 'Experienced professional in Head of Open Finance Office at Grupo Aval.', 'https://blockchainsummit.la/wp-content/uploads/2025/09/foto-ana-maria-zuluaga.png', '{Blockchain,FinTech,Innovation}', '{"friday": {"end": "17:00", "start": "09:00"}, "monday": {"end": "17:00", "start": "09:00"}, "tuesday": {"end": "17:00", "start": "09:00"}, "thursday": {"end": "17:00", "start": "09:00"}, "wednesday": {"end": "17:00", "start": "09:00"}}', NOW(), 'Grupo Aval', 'https://twitter.com/ana-maria-zuluaga', NOW(), NULL),

('alireza-siadat', 'Alireza Siadat', 'Head of Strategy and Policy', 'https://linkedin.com/in/alireza-siadat', 'Experienced professional in Head of Strategy and Policy at 1inch.', 'https://blockchainsummit.la/wp-content/uploads/2025/09/foto-alireza-siadat.png', '{Blockchain,FinTech,Innovation}', '{"friday": {"end": "17:00", "start": "09:00"}, "monday": {"end": "17:00", "start": "09:00"}, "tuesday": {"end": "17:00", "start": "09:00"}, "thursday": {"end": "17:00", "start": "09:00"}, "wednesday": {"end": "17:00", "start": "09:00"}}', NOW(), '1inch', 'https://twitter.com/alireza-siadat', NOW(), NULL),

('omar-castelblanco', 'Omar Castelblanco', 'Co Founder & CEO', 'https://linkedin.com/in/omar-castelblanco', 'Experienced professional in Co Founder & CEO at Relámpago Payments.', 'https://blockchainsummit.la/wp-content/uploads/2025/09/foto-omar-castelblanco.png', '{Blockchain,FinTech,Innovation}', '{"friday": {"end": "17:00", "start": "09:00"}, "monday": {"end": "17:00", "start": "09:00"}, "tuesday": {"end": "17:00", "start": "09:00"}, "thursday": {"end": "17:00", "start": "09:00"}, "wednesday": {"end": "17:00", "start": "09:00"}}', NOW(), 'Relámpago Payments', 'https://twitter.com/omar-castelblanco', NOW(), NULL);

-- Add comment explaining the purpose
COMMENT ON COLUMN public.BSL_Speakers.user_id IS 'Links speaker record to auth.users table for generic speaker detection';

-- To link a speaker to a user account later, use:
-- UPDATE public.BSL_Speakers 
-- SET user_id = 'user-uuid-here'::uuid 
-- WHERE id = 'speaker-id-here';
